workflows:
  ios-release:
    name: iOS Release Build
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      groups:
        - apple
      vars:
        BUNDLE_ID: "org.rainbowchallenge"
        XCODE_WORKSPACE: "ios/Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
      flutter: stable
      xcode: latest
      cocoapods: default
    triggering:
      events:
        - tag
      tag_patterns:
        - pattern: 'v*.*.*'
          include: true
      cancel_previous_builds: true
    scripts:
      - name: Get Flutter dependencies
        script: |
          flutter pub get
          
      - name: Install CocoaPods dependencies
        script: |
          cd ios && pod install && cd ..
          
      - name: Set up code signing
        script: |
          keychain initialize
          xcode-project use-profiles          
      - name: Increment build number
        script: |
          BUILD_NUMBER=$(($(git rev-list --count HEAD) + 1))
          echo "Build number: $BUILD_NUMBER"
          
          CURRENT_VERSION=$(grep 'version:' pubspec.yaml | sed 's/version: //g' | cut -d'+' -f1)
          echo "Current version: $CURRENT_VERSION"
          
          sed -i '' "s/version: .*/version: $CURRENT_VERSION+$BUILD_NUMBER/" pubspec.yaml
          
          cd ios
          agvtool new-version -all $BUILD_NUMBER
          agvtool new-marketing-version $CURRENT_VERSION
          cd ..
          
      - name: Flutter build ipa
        script: |
          flutter build ipa --release
            
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      
    publishing:
      email:
        recipients:
          - ieva@skyhook.se
        notify:
          success: true
          failure: true
          
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER    
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true