// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfjdA7Mlcb6NS0rk9RrTUEmL-PikhT9Ek',
    appId: '1:704936491342:web:6c60ecd65b617fea42461f',
    messagingSenderId: '704936491342',
    projectId: 'rainbow-challenge-370315',
    authDomain: 'rainbow-challenge-370315.firebaseapp.com',
    storageBucket: 'rainbow-challenge-370315.appspot.com',
    measurementId: 'G-B4N6X427HT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwJNICNAgvVveRGyk-p1nMYUL3VOBAkSE',
    appId: '1:704936491342:android:887a243c44b88e7c42461f',
    messagingSenderId: '704936491342',
    projectId: 'rainbow-challenge-370315',
    storageBucket: 'rainbow-challenge-370315.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcUk8FwlCYNBS1XiwoTSd7_YI8fTLNRf8',
    appId: '1:704936491342:ios:dbca0e8721c899c842461f',
    messagingSenderId: '704936491342',
    projectId: 'rainbow-challenge-370315',
    storageBucket: 'rainbow-challenge-370315.appspot.com',
    androidClientId: '704936491342-5kgobm3rliolel61g2lhl6oa4f86umtc.apps.googleusercontent.com',
    iosClientId: '704936491342-9athjvo98ouv8c07f56vkoblnjq3d74h.apps.googleusercontent.com',
    iosBundleId: 'org.rainbowchallenge',
  );
}
